### PR TITLE
Replace reqwest with ureq

### PR DESCRIPTION
**Pull request by Pombal**
Windows compile times decrease from 33s to 22s.

@FredrikNoren Can you please test again on Mac? I've been having issues with the download on Windows and I'm not sure if it's working as intended.

### CODE REVIEW

**Comment by pierd** [comment]
I'm getting this on macOS:
```
$ cargo run -- runtime install 0.3.1-nightly-2023-10-11
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/ambient runtime install 0.3.1-nightly-2023-10-11`
Installing runtime version: 0.3.1-nightly-2023-10-11
thread 'main' panicked at src/versions.rs:62:9:
assertion failed: reponse.has(\"Content-Length\")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by pierd** [comment]
Also adding this for easier testing: https://github.com/AmbientRun/AmbientCli/pull/8

**Comment by Pombal** [comment]
Awesome, thanks! Should be fixed now

**Review by FredrikNoren — APPROVED** [review]
Nice! Works on my mac

**Pull request merged**
